services:
  - type: web
    name: darak-invest-backend
    env: node
    region: ohio
    plan: free
    buildCommand: npm install
    startCommand: node scripts/seed.js && node src/server.js
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "5000"
      - key: JWT_SECRET
        generateValue: true
      - key: MAPBOX_TOKEN
        value: pk.eyJ1IjoidnBwLTY2IiwiYSI6ImNtcndoZW5hdzA2MGYzM3IzbTA4cW1yNnAifQ.bP-Z7H9Wn6WkgF2fXYITQw
