name: Build iOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'

      - run: flutter pub get

      - run: flutter build ios --release --no-codesign

      - uses: actions/upload-artifact@v4
        with:
          name: darak-wa-hayk-ios
          path: build/ios/iphoneos/Runner.app
